# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/booker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'src/proto/booker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16src/proto/booker.proto\x12\x06\x62ooker\"1\n\rBookerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x0e\x42ookerResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x15\n\rtool_executed\x18\x02 \x01(\x08\x32T\n\rBookerService\x12\x43\n\x12ProcessUserMessage\x12\x15.booker.BookerRequest\x1a\x16.booker.BookerResponseB)Z\'github.com/amine/syncpulse/proto/bookerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.booker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/amine/syncpulse/proto/booker'
  _globals['_BOOKERREQUEST']._serialized_start=34
  _globals['_BOOKERREQUEST']._serialized_end=83
  _globals['_BOOKERRESPONSE']._serialized_start=85
  _globals['_BOOKERRESPONSE']._serialized_end=139
  _globals['_BOOKERSERVICE']._serialized_start=141
  _globals['_BOOKERSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
