import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage, AIMessage

from src.tools.availability import check_availability
from src.tools.reservation import make_reservation
from src.agent.prompts import BOOKER_SYSTEM_PROMPT

load_dotenv()

TOOL_MAP = {
    "check_availability": check_availability,
    "make_reservation": make_reservation,
}

tools = list(TOOL_MAP.values())

SESSIONS = {}

def get_llm():
    model_name = os.getenv("MODEL_NAME")
    api_key = os.getenv("OPENROUTER_API_KEY")
    
    if not model_name or not api_key:
        raise ValueError("Missing MODEL_NAME or OPENROUTER_API_KEY in .env")

    return ChatOpenAI(
        model=model_name,
        openai_api_key=api_key,
        openai_api_base="https://openrouter.ai/api/v1",
        temperature=0,
    ).bind_tools(tools)

def run_booker(user_input: str, user_id: str = "default_user") -> str:
    llm_with_tools = get_llm()
    
    if user_id not in SESSIONS:
        SESSIONS[user_id] = []
    
    history = SESSIONS[user_id]
    messages = [SystemMessage(content=BOOKER_SYSTEM_PROMPT)] + history + [HumanMessage(content=user_input)]
    
    response = llm_with_tools.invoke(messages)
    messages.append(response)

    if hasattr(response, "tool_calls") and response.tool_calls:
        tool_results = []
        for tool_call in response.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_id = tool_call["id"]

            if tool_name in TOOL_MAP:
                tool_output = TOOL_MAP[tool_name].invoke(tool_args)
                tool_results.append(str(tool_output))
                messages.append(
                    ToolMessage(
                        content=str(tool_output),
                        tool_call_id=tool_id
                    )
                )

        final_response = llm_with_tools.invoke(messages)
        reply = final_response.content if final_response.content and final_response.content.strip() else "\n".join(tool_results)
    else:
        reply = response.content if response.content else "No output generated by agent."

    SESSIONS[user_id].append(HumanMessage(content=user_input))
    SESSIONS[user_id].append(AIMessage(content=reply))

    return reply

if __name__ == "__main__":
    test_prompt = "What open slots do you have on 2026-09-10?"
    print("Testing Complete Agent Loop...")
    print(f"User: {test_prompt}")
    try:
        result = run_booker(test_prompt, user_id="test-user")
        print(f"Agent Final Answer:\n{result}")
    except Exception as e:
        print(f"Error: {e}")